services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3310:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/0-create-airflow-db.sql:/docker-entrypoint-initdb.d/0-create-airflow-db.sql
      - ./mysql/db_movies_neflix_transact.sql:/docker-entrypoint-initdb.d/1-db_movies.sql
      - ./mysql/data_warehouse_netflix.sql:/docker-entrypoint-initdb.d/2-dw_netflix.sql
      - ./mysql/datos:/datos

  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
      - ./mongo/data:/data/init

  airflow:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: airflow
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+pymysql://root:root@mysql:3306/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./mysql/data:/data
    command: >
      bash -c "airflow db init && airflow users create 
      --username admin --password admin --firstname Admin --lastname User 
      --role Admin --email admin@example.com && airflow webserver"

volumes:
  mongodata: